# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'MIXR' do
    pod 'Alamofire'
    pod 'IQKeyboardManagerSwift', '~> 3.3'
    pod 'SwiftyJSON'
    pod 'Agrume'
    pod 'BTNavigationDropdownMenu'
    pod 'SpringIndicator'
    pod 'AlamofireImage'
    pod 'Mapbox-iOS-SDK'
    pod 'HanekeSwift'
    pod 'Player'

end

target 'MIXRTests' do
    
end

