# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'MIXR' do
pod 'Alamofire', '~> 3.0.0-beta.3'
pod 'IQKeyboardManagerSwift', '~> 3.3'
end

target 'MIXRTests' do

end

